### ISSUE TITLE
Twisted DNS - use different DNS resolver address as assigned to host

### ISSUE THREAD

**Issue by trizzosk** [thalesgroup-cert/Watcher#188]
Hi,

I am struggling with the web site monitoring feature, a bit. When you use DNS names (FQDN) for services under public domain names and use the same names internally on private addresses, the website monitoring is a bit confused....

Example -> I have a mail server under address `mail.domain.com`. Using DNS resolver assigned to host network adapter using DHCP, the hostname is resolved to private address (10.x.x.x). However the same name do have a public name - using public resolver (google, openDNS,...) I get public IP address.

Indeed it's more important to monitor public DNS records instead of private ones. Is there any option to explicitely configure DNS resolver for the docker to be used?
Thx.

**Comment by Felix83000** [comment]
Hi!

Okay, I understand the issue. You're dealing with a common scenario called "split-horizon" or "split-brain" DNS, where a DNS name resolves differently depending on whether you query from inside or outside your private network. 
You want your Watcher container's website monitoring to specifically use public DNS resolution.
Yes, you can absolutely configure specific DNS resolvers for your Watcher Docker container.

I recommend you trying something like this:

```
services:
  watcher: 
    image: your_watcher_image:tag
    # ... other service configurations ...
    dns:
      - 8.8.8.8
      - 1.1.1.1
      # - 208.67.222.222 # Example OpenDNS
    # ... rest of your service definition ...
```

Please come back to me to tell me if it works!

Thanks!
